apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: inclusion
  annotations:
    autoscaling.knative.dev/min-scale: "5"
  labels:
    app.kubernetes.io/part-of: inclusion
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
spec:
  source:
    git:
      url: https://github.com/tsalm-pivotal/emoji-inclusion.git
      ref:
        branch: main
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17"
  params:
  - name: api_descriptor
    value:
      type: openapi
      location:
        path: "/v3/api-docs"
      system: inclusion-system
      owner: team-vmware-tanzu-se
      description: "A set of API endpoints to manage the resources within the inclusion app."
  serviceClaims:
    - name: db
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ResourceClaim
        name: db-binding-compatible